# Generated by Django 4.1.1 on 2022-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RU', 'Russuian'), ('EN', 'English'), ('HE', 'Hebrew')], max_length=60)),
                ('product_type', models.CharField(choices=[('nonalcoholic', 'Non-Alcoholic'), ('beer', 'Beer'), ('vodka', 'Vodka'), ('whiskey', 'Whiskey'), ('tequila', 'Tequila'), ('gin', 'Gin'), ('liquor', 'Liquor'), ('arak', 'Arak'), ('rum', 'Rum'), ('absinthe', 'Absinthe'), ('רום', 'רום')], max_length=60)),
                ('itemName', models.CharField(max_length=60)),
                ('imageURL', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RU', 'Russuian'), ('EN', 'English'), ('HE', 'Hebrew')], max_length=60)),
                ('product_type', models.CharField(choices=[('salad', 'Salad'), ('fries', 'Fries'), ('hotdog', 'Hotdog'), ('schnitzel', 'Schnitzel')], max_length=60)),
                ('itemName', models.CharField(max_length=60)),
                ('imageURL', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RU', 'Russuian'), ('EN', 'English'), ('HE', 'Hebrew')], max_length=60)),
                ('product_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=60)),
                ('itemName', models.CharField(max_length=60)),
                ('imageURL', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, default='70', max_length=60)),
            ],
        ),
    ]
