# Generated by Django 4.1.1 on 2022-11-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="product_type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="food",
            name="product_type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="hookah",
            name="product_type",
            field=models.CharField(max_length=60),
        ),
    ]
